apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-app
  labels:
    app: retail-store-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail-store-app
  template:
    metadata:
      labels:
        app: retail-store-app
    spec:
      containers:
        - name: retail-store-app
          image: nginx:latest       
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
