apiVersion: v1
kind: Service
metadata:
  name: retail-store-app-service
spec:
  type: LoadBalancer
  selector:
    app: retail-store-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

