name: Terraform & EKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # 3️⃣ Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform -chdir=terraform init -reconfigure

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=terraform plan

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

      # 7️⃣ Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      # 8️⃣ Configure kubectl for EKS
      - name: Configure kubectl
        run: aws eks update-kubeconfig --region us-west-2 --name innovatemart-eks

      # 9️⃣ Deploy Application
      - name: Deploy App
        run: |
          chmod +x scripts/deploy-app.sh
          scripts/deploy-app.sh

      # 🔟 Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods -A
          kubectl get svc -A

